### ISSUE TITLE
Main command of the plugin

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/PluginTemplate#1]
I have setup the plugin template but how can I change the command /plugintemplate?

The output at this moment is 
Made by kangarko
Visit mineacademy.org for more information.

But how can I change that to my information?

**Comment by kangarko** [comment]
I have added new docs here you can have a look at:

https://github.com/kangarko/PluginTemplate/blob/main/src/main/java/org/mineacademy/template/command/SampleCommandGroup.java#L45-L64

Just override those methods and have a look at the parent's class where everything is located :)

**Comment by Greazi-Times** [comment]
Oke thank you 😃
