### ISSUE TITLE
Command returns a weird console output

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/PluginTemplate#2]
Every argument on every command get this weird output in my console.
And using the extend simplecommand I can not make a output with only /wing1 as the main command it always gives a help/info message
![image](https://user-images.githubusercontent.com/69437555/132710263-b217e259-0c1f-4e2a-ac76-33d3233c7afd.png)

**Comment by Greazi-Times** [comment]
I would also like to know how I can make a menu with a custom player head inside of it

**Comment by kangarko** [comment]
Hey! You can just remove these messages in the Packets class. And use "setAutoHandleHelp(false)" in the command's constructor to prevent automatically generating help. You must not use setMinArgs in your command for this to work. 

We'll always generate help in SimpleCommandGroup for the main command though. To edit it, override getHelpHeader in your class extending SimpleCommandGroup.

To make a menu with a custom player head, see the sample menu class and for the getItemAt you can return an ItemStack created by our SkullCreator class.
