### ISSUE TITLE
Build.xml Failing + Solution

### ISSUE THREAD

**Issue by 10axl** [kangarko/PluginTemplate#5]
https://github.com/kangarko/PluginTemplate/blob/0267a9b76d6b6554d74d06dd1be7f5733a5e9373/build.xml#L28

There seems to be an extra comment ending line ("-->") that snuck into the build.xml file on line 28. I linked the location above.

The issue is preventing the build.xml from being run.

**Comment by adrianjanocko** [comment]
Made a pull request for it, so kangarko don't need to. :)

**Comment by kangarko** [comment]
Thank you guys!
